name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.21"
          - "1.20"
          - "1.19"
          - "1.18"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ matrix.go }}"
          cache: true

      - name: Test
        run: |
          go test -v -coverprofile=profile.cov ./...

      - name: Send coverage
        if: always()
        uses: codecov/codecov-action@v5
        with:
          files: profile.cov
          flags: Go-${{ matrix.go }}
          token: ${{ secrets.CODECOV_TOKEN }}
